### ISSUE TITLE
Nextness is not processed correctly.

### ISSUE THREAD

**Issue by tsbertalan** [samuelsnyder/outline-todo.txt#5]
When I try to do the

    Walk dog
        buy leash@shopping
        adopt dog

example (using 4 spaces for tabs), After the edit step, where I enter the two sub-items, `t ol import` appears to be called automatically. At this point, I do not have `buy leash @shopping` in my todo.txt, as claimed by the readme, but instead I have `Walk dog`, and the file `WalkDog.ol.txt` contains only lines 2 and 3 from above, still indented four spaces.

**Comment by samuelsnyder** [comment]
Thanks for the feedback. By default, the tab character is recognized as an outline indent. To change this, go to line 22 and change

`OL_INDENT_CHAR="\t"`

to (with four spaces, not one. It looks like one because of GitHub's formatting):

`OL_INDENT_CHAR="    "` # should be four spaces, looks like 1 due to github formatting

I'll need to put a note about this in the readme and help. Thanks for letting me know.

**Comment by tsbertalan** [comment]
Yup, that does it. Thanks!
